services:
  - type: web
    name: healthconnect-backend
    env: node
    rootDir: HealthConnect-Backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5001
      - key: SKIP_DB_SYNC
        value: "true"
      - key: JWT_SECRET
        generateValue: true
      - key: GROQ_API_KEY
        sync: false
